$path = "C:\Users\Sree Vyshnavi\Desktop\Capstone\portfolio_intelligence.html"
$content = [System.IO.File]::ReadAllText($path)

$target = 'n==="action"&&s.jsxs("div",{className:"bg-acies-offwhite dark:bg-white/5 p-6 border-l-4 border-green-500 space-y-4",children:[s.jsxs("div",{className:"flex items-center justify-between border-b border-black/5 dark:border-white/5 pb-3",children:[s.jsx("span",{className:"text-[10px] font-bold uppercase tracking-wider opacity-50 text-acies-gray dark:text-white",children:"Reported Metric Value"}),s.jsx("span",{className:"text-2xl font-display text-acies-yellow",children:r.value})]}),s.jsxs("div",{children:[s.jsxs("h4",{className:"text-[9px] font-bold text-green-500 uppercase flex items-center gap-1",children:[s.jsx(sN,{size:10}),"Recommended Action"]}),s.jsx("p",{className:"text-xs text-acies-gray dark:text-white/80 leading-relaxed mt-1.5 font-medium",children:r.action})]})]})'

# Verify if target exists
if ($content.Contains($target)) {
    Write-Output "Found target string!"
    
    $replacement = 'n==="action"&&s.jsxs("div",{className:"space-y-6",children:[s.jsxs("div",{className:"bg-acies-offwhite dark:bg-white/5 p-6 border-l-4 border-green-500 space-y-4",children:[s.jsxs("div",{className:"flex items-center justify-between border-b border-black/5 dark:border-white/5 pb-3",children:[s.jsx("span",{className:"text-[10px] font-bold uppercase tracking-wider opacity-50 text-acies-gray dark:text-white",children:"Reported Metric Value"}),s.jsx("span",{className:"text-2xl font-display text-acies-yellow",children:r.value})]}),s.jsxs("div",{children:[s.jsxs("h4",{className:"text-[9px] font-bold text-green-500 uppercase flex items-center gap-1",children:[s.jsx(sN,{size:10}),"Recommended Action"]}),s.jsx("p",{className:"text-xs text-acies-gray dark:text-white/80 leading-relaxed mt-1.5 font-medium",children:r.action})]})]}),s.jsxs("section",{className:"space-y-3",children:[s.jsxs("div",{className:"flex items-center gap-2 text-acies-gray dark:text-white",children:[s.jsx(iN,{size:14,className:"text-acies-yellow"}),s.jsx("h4",{className:"text-[10px] font-bold uppercase tracking-wider",children:"Mathematical Formula"})]}),s.jsx("div",{className:"bg-black/5 dark:bg-white/5 p-5 rounded-sm flex items-center justify-center border border-black/5 dark:border-white/5",children:s.jsx("code",{className:"font-mono text-xs md:text-sm font-bold text-acies-gray dark:text-white text-center select-all",children:r.formula})}),s.jsx("p",{className:"text-[10px] opacity-60 leading-relaxed italic text-acies-gray dark:text-white",children:r.formulaDescription})]}),s.jsxs("section",{className:"space-y-3",children:[s.jsxs("div",{className:"flex items-center gap-2 text-acies-gray dark:text-white",children:[s.jsx(Fb,{size:14,className:"text-acies-yellow"}),s.jsx("h4",{className:"text-[10px] font-bold uppercase tracking-wider",children:"Source Data Lineage"})]}),s.jsxs("p",{className:"text-xs opacity-60 leading-relaxed text-acies-gray dark:text-white",children:["Raw fields utilized from ",s.jsx("code",{className:"font-mono text-[10px] bg-black/5 dark:bg-white/5 px-1 py-0.5",children:"FMCG Multi-Country Sales Dataset"}),"."]}),s.jsx("div",{className:"border border-black/5 dark:border-white/5 rounded-sm divide-y divide-black/5 dark:divide-white/5 overflow-hidden",children:r.columns.map((l,c)=>s.jsxs("div",{className:"p-4 bg-acies-offwhite/30 dark:bg-white/2",children:[s.jsxs("div",{className:"flex justify-between items-baseline mb-1",children:[s.jsx("span",{className:"font-mono text-xs text-acies-yellow font-bold",children:l.name}),s.jsx("span",{className:"text-[8px] opacity-40 uppercase font-bold tracking-wider text-acies-gray dark:text-white",children:l.type})]}),s.jsx("p",{className:"text-[10px] opacity-60 leading-normal text-acies-gray dark:text-white",children:l.desc})]},c))})]})]})'
    
    $newContent = $content.Replace($target, $replacement)
    [System.IO.File]::WriteAllText($path, $newContent, [System.Text.Encoding]::UTF8)
    Write-Output "Successfully updated portfolio_intelligence.html!"
} else {
    Write-Output "ERROR: Target string not found!"
}
